<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>txt</string>
    </array>
    <key>name</key>
    <string>Plain Text</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>\[\[([^\[\]]+)\]\]</string>
            <key>name</key>
            <string>entity.other.attribute-name.variable.wtl</string>
        </dict>
        <dict>
            <key>match</key>
            <string>((?&lt;!\-)\-{79}(?!\-))</string>
            <key>name</key>
            <string>keyword.control.wtl</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(:&lt;#[^\&gt;]*&gt;)</string>
            <key>name</key>
            <string>support.function.perl</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(((?&lt;!\.)\.{49}(?!\.))|((?&lt;!\+)\+{24}(?!\+))|(&lt;[^\&gt;]+&gt;)|(https?://[^\s]+))</string>
            <key>name</key>
            <string>string.quoted.double.xml</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>text.plain</string>
</dict>
</plist>
